# Generated by Django 5.0 on 2024-01-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_subadminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='MemberDocs/')),
                ('amount', models.IntegerField()),
                ('details', models.CharField(max_length=50)),
                ('renttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_renttype')),
            ],
        ),
    ]
