# Generated by Django 5.0 on 2024-01-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rent',
        ),
    ]
