# Generated by Django 5.0 on 2024-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimage', models.FileField(upload_to='MemberDocs/')),
            ],
        ),
    ]
