# Generated by Django 5.0 on 2024-01-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_tbl_rentgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rent',
            name='renttype',
        ),
        migrations.DeleteModel(
            name='tbl_rentgallery',
        ),
        migrations.DeleteModel(
            name='tbl_rent',
        ),
    ]
