# Generated by Django 5.0 on 2024-01-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_subadminregistration'),
        ('Guest', '0007_tbl_userregistration'),
        ('Owner', '0005_remove_tbl_rent_renttype_delete_tbl_rentgallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='MemberDocs/')),
                ('amount', models.IntegerField()),
                ('details', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_ownerregistration')),
                ('renttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_renttype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rentgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimage', models.FileField(upload_to='MemberDocs/')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_rent')),
            ],
        ),
    ]
