# Generated by Django 5.0 on 2024-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rent',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
