# Generated by Django 5.0 on 2024-02-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_tbl_ownercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ownercomplaint',
        ),
    ]
