# Generated by Django 5.0 on 2024-02-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0010_tbl_ownercomplaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_ownercomplaint',
            old_name='complaint_name',
            new_name='complainttype',
        ),
    ]
