# Generated by Django 5.0 on 2023-12-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_state',
        ),
    ]
