# Generated by Django 5.0 on 2023-12-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_subadminregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subadminregistration',
        ),
    ]
