# Generated by Django 5.0 on 2023-12-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_subadminregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subadminregistration',
        ),
    ]
