# Generated by Django 5.0 on 2024-02-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_subadminregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_subadminregistration',
            new_name='tbl_officer',
        ),
    ]
