# Generated by Django 5.0 on 2024-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_tbl_subadminregistration_tbl_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complainttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(max_length=50)),
            ],
        ),
    ]
