# Generated by Django 5.0 on 2024-01-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ownerregistration',
        ),
    ]
