# Generated by Django 5.0 on 2024-01-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ownerregistration',
        ),
    ]
