# Generated by Django 5.0 on 2024-01-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_ownerregistration',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
