# Generated by Django 5.0 on 2024-01-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ownerregistration',
            name='status',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
