# Generated by Django 5.0 on 2024-01-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0008_tbl_ownerregistration_status'),
        ('Owner', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='MemberDocs/')),
                ('content', models.CharField(max_length=50)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
