# Generated by Django 5.0 on 2024-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='MemberDocs/')),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
