# Generated by Django 5.0 on 2024-01-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userrequest',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
