# Generated by Django 5.0 on 2024-02-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_userrequest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userrequest',
        ),
    ]
