# Generated by Django 5.0 on 2024-02-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_ownerregistration_status'),
        ('Owner', '0007_tbl_rent_status'),
        ('User', '0007_delete_tbl_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='MemberDocs/')),
                ('content', models.CharField(max_length=50)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('status', models.CharField(default=0, max_length=50)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
