# Generated by Django 5.0 on 2024-02-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_usercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_usercomplaint',
        ),
    ]
