# Generated by Django 5.0 on 2024-03-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0011_rename_complaint_name_tbl_ownercomplaint_complainttype'),
        ('User', '0013_delete_tbl_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('user_review', models.CharField(max_length=50)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_rent')),
            ],
        ),
    ]
