# Generated by Django 5.0 on 2024-03-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_adminlogin'),
        ('User', '0015_tbl_userfeedback_rename_rent_tbl_userrating_reant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_userregistration'),
        ),
    ]
