# Generated by Django 5.0 on 2024-03-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_userfeedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_userrating',
            old_name='reant',
            new_name='rent',
        ),
    ]
